### ISSUE TITLE
Broadcast Psbt on testnet

### ISSUE THREAD

**Issue by skyrover7** [secretkeylabs/sats-connect-example#22]
i am creating a psbt following the sats connect example. i am able to create it and also sign it. If i set `broadcast: false` i get back the signed psbt. if i set it to true, it shows it correctly in the wallet, but then when i click confirm it shows a 400 error

**Comment by victorkirov** [comment]
Could you please give a bit more info on the PSBT? There are quite a few things that could go wrong.

It might be better to join our discord so we can help you there in chat.

**Comment by skyrover7** [comment]
@victorkirov sure thing, can you share an invite please?

**Comment by victorkirov** [comment]
Here's the invite link as of 2024-02-07: https://discord.gg/5yZXYvkt

Please ping me via DM to add you to the dev role so you can post in the developer channel

**Comment by skyrover7** [comment]
DM sent

**Comment by skyrover7** [comment]
turns out it was an issue in how the psbt was being constructed. @victorkirov thanks for the guidance. turning on developer tool within the wallet extension window and checking the network tab gave more details than just the 400 error. that allowed me to debug!
