### ISSUE TITLE
How to form a OP_RETURN output with sats-connect

### ISSUE THREAD

**Issue by abhishek-Kumar009** [secretkeylabs/sats-connect-example#7]
Hey guys i have been trying to form OP_RETURN output using sats-connect

I have to send an EVM address (20bytes) in OP_RETURN data for my dApp 

Please help me here:
I've reached this far in figuring this out 
```
tx.addOutput({
      script: btc.Script.encode([
        'RETURN',
        new TextEncoder().encode('abc')
      ]),
      amount: 0n
    })
```

**Comment by yknl** [comment]
Added in https://github.com/secretkeylabs/sats-connect-example/pull/6
